[paths]
ringbuffer_dir = /dev/shm/hf25
output_dir = /data0/
channel = ch0

[sounding]
#  ; 7.5 minutes
sounding_interval_sec = 450       
transmitter="Ramfjordmoen"
receiver="Tromso"

[rf]
sample_rate = 25000000
center_frequency = 12500000
decimation = 250

[frequency_sweep]
freq_start = 1000000
freq_stop = 18000000
freq_step = 50000

[pulses]
ipp_us = 10000
n_ipp = 64

[timing]
offset_us = -320

[processing]
wait_for_data = True