#
# Configuration for Server




[stations]
# ROTHR and JORN are approximate, as there are multiple transmitters, and we dont't know which is which
station_info={"SGO":{"name":"SGO",
	             "lat":67.36369337350563,
	             "lon":26.634311805059543},
	      "TGO":{"name":"TGO",
	             "lat":69.66174439007057,
		     "lon":18.939127366530286},
	      "DOB":{"name":"Dombås",
	             "lat":62.073,
		     "lon":9.111},
	      "Ramfjordmoen":{"name":"Ramfjordmoen",
	                      "lat":69.58187184247221,
			      "lon":19.220853348827067},
	      "ROTHR":{"name":"ROTHR",
	             "lat":36.11793762278912, 
		     "lon":-82.5807086169964},
	      "JORN":{"name":"JORN", 
	             "lat":-23.853424758715892,
		     "lon":125.07620821000198},
	      "Juliusruh":{"name":"Juliusruh", 
	             "lat":54.628740389301186,
		     "lon":13.374299986524846}
	      }
links=[["SGO","TGO"],
       ["Ramfjordmoen","TGO"],
       ["ROTHR","TGO"],
       ["JORN","TGO"],
       ["Juliusruh","TGO"],
       ["SGO","DOB"],
       ["Ramfjordmoen","DOB"],
       ["ROTHR","DOB"],
       ["JORN","DOB"],
       ["Juliusruh","DOB"]]
