#
# Configuration for TGO
#
# 25 MHz ringbuffer data provided by N200 data
# Include Ramfjordmoen digisonde
# Include SGO LFM sounder
# Include detection of unknown 100 kHz and 125 kHz sounders
# 
#
[config]

# specify that processing occurs on a live ringbuffer
# that continuously gets added more measurements by
# the recorder (and old files are removed to keep buffer a constant size)
# this requires the processing to sometimes wait for more data

receiver_station_name="TGO"
realtime=true
# recording settings and data directory
channel=["ch0"]
sample_rate=25000000
center_freq=12.5e6
# use ram dis
data_dir="/dev/shm/hf25"
# 300 seconds is 30 GB
ringbuffer_max_age_sec=300
# delete older files
ringbuffer_cleanup=true

output_dir="/mnt/shovel/ionosonde"



[detection]
# options for chirp detection
threshold_snr=13.0
max_simultaneous_detections=5
min_detections=3
step=3
n_samples_per_block=5000000
minimum_frequency_spacing=0.2e6
chirp_rates=[100e3,125e3]


[lfm]
# ionogram calc (spectram parameters)
save_raw_voltage=false
range_resolution=2e3
frequency_resolution=50e3
max_range_extent=1000e3
n_downconversion_threads=3
decimation=1250
min_range=200e3
max_range=1500e3
manual_range_extent=true
max_freq=16e6
min_freq=0.5e6
manual_freq_extent=true
storage_snr_threshold=2
maximum_analysis_frequency=25e6
minimum_analysis_frequency=0
sounder_timings=[[{"chirp-rate":500.0084e3,"rep":60.0,"chirpt":54.0,"id":1,"transmit_name":"SGO"}]]

# display the detected ionograms
#plot_timings=false
#debug_timings=false
[transfer]
copy_to_server=true
copy_destination="j@4.235.86.214:/var/www/html/iono/"

[digisonde]
# Ramfjordmoen Digisonde
# every 7.5 minutes
sounding_interval_sec = 450       
transmitter_station_name="Ramfjordmoen"
# don't save values below this threshold
snr_threshold=2
decimation = 250
freq_start = 1000000
freq_stop = 18000000
freq_step = 50000
ipp_us = 10000
n_ipp = 64
offset_us = -330
wait_for_data = true



[digisonde-Juliusruh]
# Julius Digisonde
# every 5 minutes
sounding_interval_sec = 300
transmitter_station_name="Juliusruh"
# don't save values below this threshold
snr_threshold=2
decimation = 250
freq_start = 1010000
freq_stop = 14000000
freq_step = 50000
ipp_us = 10000
n_ipp = 16
# 1700 km Juliusruh-TGO
offset_us = 5000
wait_for_data = true
start_offset=196
sum_ox=true
# daytime only
sounding_hrs=[8,18]

[digisonde-JuliusruhN]
# Julius Digisonde
# every 5 minutes
sounding_interval_sec = 300
transmitter_station_name="Juliusruh"
# don't save values below this threshold
snr_threshold=2
decimation = 250
freq_start = 1010000
freq_stop = 10000000
freq_step = 25000
ipp_us = 10000
n_ipp = 16
# 1700 km Juliusruh-TGO
offset_us = 5000
wait_for_data = true
start_offset=196
sum_ox=true
# night only
sounding_hrs=[18,8]


[stations]
# ROTHR and JORN are approximate, as there are multiple transmitters, and we dont't know which is which
station_info={"SGO":{"name":"SGO",
	             "lat":67.36369337350563,
	             "lon":26.634311805059543},
	      "TGO":{"name":"TGO",
	             "lat":69.66174439007057,
		     "lon":18.939127366530286},
	      "Ramfjordmoen":{"name":"Ramfjordmoen",
	                      "lat":69.58187184247221,
			      "lon":19.220853348827067},
	      "ROTHR":{"name":"ROTHR",
	             "lat":36.11793762278912, 
		     "lon":-82.5807086169964},
	      "JORN":{"name":"JORN", 
	             "lat":-23.853424758715892,
		     "lon":125.07620821000198},
	      "Juliusruh":{"name":"Juliusruh", 
	             "lat":54.628740389301186,
		     "lon":13.374299986524846}
	      }
links=[["SGO","TGO"],
       ["Ramfjordmoen","TGO"],
       ["ROTHR","TGO"],
       ["JORN","TGO"],
       ["Juliusruh","TGO"]]
