/home/hfrx2/src/git/chirpsounder2/logs/detect.log
/home/hfrx2/src/git/chirpsounder2/logs/plot_rtf.log
/home/hfrx2/src/git/chirpsounder2/logs/digisonde.log
/home/hfrx2/src/git/chirpsounder2/logs/ringbuffer.log
/home/hfrx2/src/git/chirpsounder2/logs/housekeeping.log
/home/hfrx2/src/git/chirpsounder2/logs/detections2metadata.log
/home/hfrx2/src/git/chirpsounder2/logs/sync.log
/home/hfrx2/src/git/chirpsounder2/logs/ionograms.log
/home/hfrx2/src/git/chirpsounder2/logs/thor.log
/home/hfrx2/src/git/chirpsounder2/logs/plot_detectionfiles.log
/home/hfrx2/src/git/chirpsounder2/logs/timings.log
/home/hfrx2/src/git/chirpsounder2/logs/plot_ionograms.log
{
    size 10M
    rotate 5
    compress
    missingok
    notifempty
    copytruncate
}