#
# Configuration for W2NAF, Scranton, PA
#
# 25 MHz ringbuffer data from a USRP N200.
# Initially only detect unknown 100 kHz and 125 kHz chirp sounders
# such as ROTHR and JORN using detect_chirps.py.
#
[config]

receiver_station_name="W2NAF"
realtime=true
serendipitous=true
serendipitous_ionogram_workers=4
channel=["ch0"]
sample_rate=25000000
center_freq=12.5e6
# W2NAF has a 100 GB tmpfs at /mnt/ramdisk. 25 MHz complex int16
# raw voltage is about 100 MB/s, so 950 s uses about 95 GB.
data_dir="/mnt/ramdisk/hf25"
ringbuffer_max_age_sec=950
ringbuffer_cleanup=true
output_dir="/home/hamsci/data/chirpsounder2"
# W2NAF GPSDO locked on 2026-05-31. Require lock before recording.
require_gps_lock=true
gps_lock_timeout_sec=-1


[detection]
threshold_snr=13.0
max_simultaneous_detections=5
min_detections=10
step=1
n_samples_per_block=5000000
realtime_detection_lag_sec=5
minimum_frequency_spacing=0.2e6
chirp_rates=[100e3,125e3]
propagation_range_bands="auto"
propagation_range_transmitters=["NIC","JORN","ROTHR1","ROTHR2","ROTHR3"]
propagation_range_factor="auto"
propagation_band_fraction=0.15
detection_range_filter=true
detection_range_filter_min_km=0
detection_range_filter_max_km="auto_jorn"


[lfm]
save_raw_voltage=false
downconversion_filter="fir"
range_resolution=2e3
frequency_resolution=50e3
max_range_extent=4000e3
serendipitous_range_quantization_km=2000
serendipitous_range_extent_km=4000
serendipitous_range_buffer_km=0
max_ionogram_frequency_steps=512
n_downconversion_threads=1
downconversion_block_samples=4000
decimation=625
min_range=200e3
max_range=4000e3
manual_range_extent=true
max_freq=25e6
min_freq=0.5e6
manual_freq_extent=true
storage_snr_threshold=10
maximum_analysis_frequency=25e6
minimum_analysis_frequency=0
sounder_timings=[]


[rtf]
links=[]


[transfer]
copy_to_server=true
copy_destination="https://juha.no/upload.php"
